CREATE TABLE IF NOT EXISTS PRODUCT (
    ID SERIAL PRIMARY KEY,
    BARCODE VARCHAR ( 250 ) NOT NULL,
    NAME VARCHAR ( 250 ) NOT NULL,
    DESCRIPTION VARCHAR ( 250 ) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    SALE_PRICE INTEGER NOT NULL,
    PURCHASE_PRICE INTEGER NOT NULL,
    CATEGORY_ID VARCHAR ( 50 ) NOT NULL,
    SUPPLIER_ID VARCHAR ( 50 ) NOT NULL,
    DATE_ADDED TIMESTAMP NOT NULL,
    LAST_UPDATE TIMESTAMP
);